CREATE PROC FI_SP_ConsBeneficiario
	@ID			BIGINT = 0,
	@IDCLIENTE	BIGINT = 0
AS
BEGIN
	IF(ISNULL(@IDCLIENTE,0) > 0)
		SELECT NOME, IDCLIENTE, ID, CPF FROM BENEFICIARIOS WITH(NOLOCK) WHERE IDCLIENTE = @IDCLIENTE
	ELSE IF(ISNULL(@ID,0) > 0)
		SELECT NOME, IDCLIENTE, ID, CPF FROM BENEFICIARIOS WITH(NOLOCK) WHERE ID = @ID
	ELSE
		SELECT NOME, IDCLIENTE, ID, CPF FROM BENEFICIARIOS WITH(NOLOCK)
END